In [2]:
import numpy as np
import scipy.signal as sig

# (7.4.2) Resposta dinâmica a partir das equações de estado

Dada uma entrada $u(t)$ e uma condição inicial dos estados $\mathbf{x}(0)$, podemos resolver a equação diferencial (matricial) dos estados e determinar a saída do sistema. Isso pode ser feito com a transformada de Laplace.

$$
\begin{align*}
    \mathbf{\dot{x}} &= \mathbf{Fx+G}u\\
    \mathcal{L}\{\mathbf{\dot{x}}\} &= \mathcal{L}\{\mathbf{Fx+G}u\}\\
    s\mathbf{X}(s)-\mathbf{x}(0) &= \mathbf{FX}(s)+\mathbf{G}U(s)\\
    s\mathbf{X}(s)-\mathbf{FX}(s)&=\mathbf{x}(0)+\mathbf{G}U(s)\\
    (s\mathbf{I-F})\mathbf{X(s)} &= \mathbf{x}(0)+\mathbf{G}U(s)\\
    \mathbf{X(s)} &= (s\mathbf{I-F})^{-1}\mathbf{x}(0)+(s\mathbf{I-F})^{-1}\mathbf{G}U(s)\\
\end{align*}
$$

O termo $(s\mathbf{I-F})^{-1}\mathbf{x}(0)$ é a resposta de entrada nula, devido sua independência da função de entrada.

O termo $(s\mathbf{I-F})^{-1}\mathbf{G}U(s)$ é a resposta de estado nulo, devido sua independência das condições iniciais.

Para determinar os estados no domínio do tempo $\mathbf{x}(t)$ bastaria tirar a transformada inversa. Assim teríamos a resposta de cada um dos estados em função do tempo.

## Sinal de saída e função de transferência

Olhando agora o sinal de saída:
$$
\begin{align*}
    y &= \mathbf{Hx} + Ju\\
    Y(s) &= \mathbf{HX(s)} + JU(s)
\end{align*}
$$

Substituindo o que encontramos para $\mathbf{X}(s)$:
$$
\begin{align*}
    Y(s) &= \mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{x}(0)+\mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{G}U(s) + JU(s)
\end{align*}
$$

Colocando $U(s)$ em evidência agora:
$$
\begin{align*}
    Y(s) &= \mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{x}(0)+\left[\mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{G} + D\right]U(s)
\end{align*}
$$

Quando as condições iniciais são nulas $\mathbf{x}(0)=\mathbf{0}$, o termo que sobra é um escalar:
$$
\begin{align*}
    Y(s) &= \left[\mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{G} + J\right]U(s)\\
    \frac{Y(s)}{U(s)} &= \mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{G} + J
\end{align*}
$$

Reconhecemos a última equação como a função de transferência do sistema definida em termos das matrizes da representação de espaço de estados.

## Pólos de um sistema no espaço de estados (Autovalores)

Na equação da função de transferência, o termo principal é $(s\mathbf{I-F})^{-1}$. Sabemos que a inversa de qualquer matriz pode ser descrita como sua adjunta divido pelo seu determinante. O que vai sobrar no denominador da função de transferência, portanto, é $\det (s\mathbf{I-F})$.

Sabemos que os pólos são as raízes do denominador de uma função de transferência. Ora, se o denominador é dado pelo determinante acima, então os pólos do sistema são dados pelas soluções da equação:
$$
\begin{align}
\det (s\mathbf{I-F}) = 0
\end{align}
$$

Os valores de $s$ que satisfazem essa equação são chamados em álgebra linear de **autovalores da matriz** e de desempenham um papel importante em vários problemas de Engenharia. 

Em Python vc pode calcular os autovalores do sistema usando a funçao "pole()" da biblioteca *control*, ou usar a biblioteca *linalg* do NumPy para resolver o problema de autovalor diretamente na matriz de estados do sistema. Note, porém, que a função "eig()" do NumPy devolve não apenas os autovalores, mas também os [autovetores](https://pt.wikipedia.org/wiki/Autovalores_e_autovetores) associados também.

<p align="center">
<img src="Ex7.12.svg" width="80%">
</p>

Solução manual (você precisa saber fazer manualmente *pelo menos* os casos de ordem 2!):

$$
\begin{align*}
    s\mathbf{I-F} &= s\left[\begin{array}{cc}1 & 0\\0 & 1\end{array}\right]-\left[\begin{array}{cc}-7 & -12\\1 & 0\end{array}\right]\\
    &= \left[\begin{array}{cc}s+7 & 12\\-1 & s\end{array}\right]
\end{align*}
$$

A inversa da matriz é:
$$
\begin{align*}
    (s\mathbf{I-F})^{-1} &= \frac{\left[\begin{array}{cc}s & -12\\1 & s+7\end{array}\right]}{s(s+7)+12}
\end{align*}
$$

Faz-se agora o produto pela esquerda:
$$
\begin{align*}
    \mathbf{H}(s\mathbf{I-F})^{-1} &= \frac{\left[\begin{array}{cc}1 & 2\end{array}\right]\left[\begin{array}{cc}s & -12\\1 & s+7\end{array}\right]}{s(s+7)+12}\\
    &= \frac{\left[\begin{array}{cc}s+2 & 2s+2\end{array}\right]}{s^2+7s+12}
\end{align*}
$$

E o resultado com o produto pela direita:
\begin{align*}
    \mathbf{H}(s\mathbf{I-F})^{-1}\mathbf{G} &= \frac{\left[\begin{array}{cc}s+2 & 2s+2\end{array}\right]\left[\begin{array}{c}1 \\ 0\end{array}\right]}{s^2+7s+12}\\
    & = \frac{s+2}{s^2+7s+12}
\end{align*}

Em Python, você pode implementar essas contas usando o pacote simbólico. Porém, o pacote *control* faz de um jeito mais ágil usando as definições próprias voltadas para Engenharia

In [4]:
import numpy as np
import control as ct

# Definindo as matrizes
F = np.matrix([[-7,-12],[1,0]])
G = np.matrix([[1],[0]])
H = np.matrix([1,2])
J = 0

# Definindo o sistema como espaço de estados
sys = ct.ss(F,G,H,J)
print(sys)

# Calculando a função de transferência pelo objeto espaço de estados
FT = ct.tf(sys)
print(FT)


<LinearIOSystem>: sys[2]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (2): ['x[0]', 'x[1]']

A = [[ -7. -12.]
     [  1.   0.]]

B = [[1.]
     [0.]]

C = [[1. 2.]]

D = [[0.]]


    s + 2
--------------
s^2 + 7 s + 12



**Exercício**: Calcule manualmente e confira sua resposta com Python, a função de transferência do sistema

$$
\begin{align}
\dot{\mathbf{x}} &= \left[\begin{array}{cc}-1 & 7\\ 9 & 0\end{array}\right]\mathbf{x} + \left[\begin{array}{cc} 5 \\ -3\end{array}\right]u\\
y &= \left[\begin{array}{cc}3 & 2\end{array}\right]\mathbf{x} 
\end{align}
$$

## Zeros do sistema

Na descrição entrada-saída (função de transferência) de um sistema, definimos zeros de uma forma bem matemática: são as raízes do numerador.

No entanto, os zeros possuem uma definição um pouco mais física. São chamados zeros os modos (exponenciais) que, se colocados na entrada do sistema, produzem uma saída identicamente nula. Isso permite estabelecer as expressões que definem os zeros do sistema em função das matrizes de espaço de estados.

Para achar os zeros, basta resolver a equação polinomial:
$$
\begin{align*}
\det\,\left[\begin{array}{cc}s\mathbf{I-F} & -\mathbf{G}\\ \mathbf{H} & J\end{array}\right]=0 
\end{align*}
$$

<p align="center">
<img src="Ex7.13.svg" width="80%">
</p>

**Solução**: Precisamos montar a matriz. No caso, já calculamos $s\mathbf{I-F}$ no exemplo anterior, então basta concatenar as demais:
$$
\begin{align*}
    s\mathbf{I-F} &= \left[\begin{array}{cc}s+7 & 12\\-1 & s\end{array}\right]\\
    \Rightarrow \left[\begin{array}{ccc}s\mathbf{I-F} & -\mathbf{G}\\ \mathbf{H} & J\end{array}\right]&=
    \left[\begin{array}{ccc}s+7 & 12 & -1\\-1 & s & 0\\ 1 & 2 & 0 \end{array}\right]
\end{align*}
$$

Basta agora calcular o determinante.
$$
\begin{align*}
    \det \left[\begin{array}{ccc}s+7 & 12 & 1\\-1 & s & 0\\ 1 & 2 & 0 \end{array}\right] &= 
    \det \left[\begin{array}{cc}-1 & s \\ 1 & 2 \end{array}\right] = -2-s 
\end{align*}
$$

Igualando a zero, temos:
$$
\begin{align*}
    -2-s =0 \Rightarrow s = -2
\end{align*}
$$

Em Python, a função "zero()" é capaz de determinar os zeros a partir da representação do sistema

In [ ]:
ct.zero(sys)

array([-2.+0.j])

<p align="center">
<img src="Ex7.14.svg" width="80%">
</p>

Esse é um problema de ordem elevada, então vamos resolver com Python

In [8]:
import scipy.signal as sig

F = np.matrix([[0,2,0,0,0],[-0.1,-0.35,0.1,0.1,0.75],[0,0,0,2,0],[.4,.4,-.4,-1.4,0],[0,-.03,0,0,-1]])
G = np.matrix([[0],[0],[0],[0],[1]])
H2 = np.matrix([0,0,1,0,0])
J = 0

sys = ct.ss(F,G,H2,J)
#sys = sig.StateSpace(F,G,H2,J)
print(sys)


<LinearIOSystem>: sys[6]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (5): ['x[0]', 'x[1]', 'x[2]', 'x[3]', 'x[4]']

A = [[ 0.    2.    0.    0.    0.  ]
     [-0.1  -0.35  0.1   0.1   0.75]
     [ 0.    0.    0.    2.    0.  ]
     [ 0.4   0.4  -0.4  -1.4   0.  ]
     [ 0.   -0.03  0.    0.   -1.  ]]

B = [[0.]
     [0.]
     [0.]
     [0.]
     [1.]]

C = [[0. 0. 1. 0. 0.]]

D = [[0.]]



In [12]:
# Podemos obter também a função de transferência do sistema
#ft = ct.ss2tf(sys)
ct.tf(sys)
num,den = ct.tfdata(sys)
print(num)
print(den)
#z,p,k = sig.ss2zpk(sys.A,sys.B,sys.C,sys.D)
#den[-1]=0
#ft = sig.TransferFunction(num,den)
#print(ft)
#p
print(ct.pole(sys))
print(ct.zero(sys))

[[array([8.62946505e-17, 6.00000000e-01, 1.20000000e+00])]]
[[array([1.00000000e+00, 2.75000000e+00, 3.22250000e+00, 1.88150000e+00,
       4.18000000e-01, 3.74700271e-16])]]
[-6.37107917e-01+0.6668794j -6.37107917e-01-0.6668794j
  7.00736404e-16+0.j        -5.07486111e-01+0.j
 -9.68298056e-01+0.j       ]
[-2.+0.j]


In [14]:
ct.damp(sys)

_____Eigenvalue______ Damping___ Frequency_
   -0.6371   +0.6669j     0.6908     0.9223
   -0.6371   -0.6669j     0.6908     0.9223
 7.007e-16                     1 -7.007e-16
   -0.5075                     1     0.5075
   -0.9683                     1     0.9683


(array([9.22298560e-01, 9.22298560e-01, 7.00736404e-16, 5.07486111e-01,
        9.68298056e-01]),
 array([ 0.69078273,  0.69078273, -1.        ,  1.        ,  1.        ]),
 array([-6.37107917e-01+0.6668794j, -6.37107917e-01-0.6668794j,
         7.00736404e-16+0.j       , -5.07486111e-01+0.j       ,
        -9.68298056e-01+0.j       ]))

In [ ]:
# A FT está na forma de um objeto Python. Vamos extrair as informações principais, numerador e denominador
#num,den=ct.tfdata(ft)

#print(num[0][0])
#print(den[0][0])
den[-1]=0
den

array([1.    , 2.75  , 3.2225, 1.8815, 0.418 , 0.    ])

In [ ]:
(np.linalg.eig(sys.A))

(array([-6.37107917e-01+0.6668794j, -6.37107917e-01-0.6668794j,
         7.00736404e-16+0.j       , -5.07486111e-01+0.j       ,
        -9.68298056e-01+0.j       ]),
 matrix([[-1.16823286e-01+0.19252486j, -1.16823286e-01-0.19252486j,
          -7.07106781e-01+0.j        ,  4.87131214e-01+0.j        ,
           5.88736883e-01+0.j        ],
         [-2.69809105e-02-0.10028308j, -2.69809105e-02+0.10028308j,
          -2.32710799e-16+0.j        , -1.23606163e-01+0.j        ,
          -2.85036390e-01+0.j        ],
         [ 8.79719828e-01+0.j        ,  8.79719828e-01-0.j        ,
          -7.07106781e-01+0.j        ,  8.37949352e-01+0.j        ,
           6.36048871e-01+0.j        ],
         [-2.80238233e-01+0.29333352j, -2.80238233e-01-0.29333352j,
          -1.71735054e-16+0.j        , -2.12623829e-01+0.j        ,
          -3.07942443e-01+0.j        ],
         [ 3.99021736e-03+0.00095758j,  3.99021736e-03-0.00095758j,
           5.76200785e-18+0.j        ,  7.52909706e-03+0.j    

In [ ]:
# Vamos calcular os polos e zeros agora pelas raizes dos polinômios. Os resultados devem concordar
print(np.roots(ft.num))
print(np.roots(ft.den))

[-2.]
[-0.63710792+0.6668794j -0.63710792-0.6668794j -0.96829806+0.j
 -0.50748611+0.j         0.        +0.j       ]


## Estabilidade no espaço de estados

O conceito de estabilidade no espaço de estados é um pouco diferente do que aprendemos na representação entrada-saída.

Primeiramente, no espaço de estados definimos o **ponto de equilíbrio** do sistema. O ponto de equilíbrio é um vetor de estado específico que anula a derivada do vetor de estados quando a entrada é nula ($u=0$); em outras palavras, o sistema "não se mexe".

Um sistema linear possui apenas um ponto de equilíbrio, o vetor nulo $\mathbf{x}= \left[\begin{array}{cccc}0 & 0 & \ldots & 0\end{array}\right]$.

É fácil de verificar que esse é um ponto de equilíbrio. Dada a equação de estados
$$
\begin{align*}
    \mathbf{\dot{x}} &= \mathbf{Fx+G}u
\end{align*}
$$
vemos que se $u=0$ e se $\mathbf{x=0}$, então todo o lado direito se anula, o que implica que $\mathbf{\dot{x}=0}$. Ou seja, o sistema não evolui com o tempo, fica sempre no "mesmo lugar".

Definido o que é equilíbrio, podemos agora definir estabilidade.

Dizemos que um sistema é estável no espaço de estados, se, dada uma variação inicial no ponto de equilíbrio, os estados do sistema "voltarem" para o ponto de equilíbrio inicial.

Um sistema linear, portanto, será linear se, dada uma condição inicial diferente de zero do vetor de estados, o vetor $\mathbf{x}(t)$ voltar para zero em um determinado intervalo de tempo. 

Como já sabemos, o sistema é estável quando todos os seus pólos estão no semi-plano esquerdo (SPE). Como no espaço de estados os pólos são autovalores da matriz de estados $\mathbf{F}$, então o sistema será estável se todos esses autovalores tiverem parte real estritamente negativa. 

Isso garante que quando passar um longo tempo, isto é, $t\rightarrow \infty$, os estados tenderão a zero, ou seja $\mathbf{x}(t) \rightarrow \mathbf{0}$. Isso é chamado também de **estabilidade assintótica**.

## Exemplo: verifique se o sistema abaixo é estável

$$
\begin{align*}
    \dot{\mathbf{x}}= \left[\begin{array}{cc}0 &1\\ -3 & -7\end{array}\right]\mathbf{x} +
    \left[\begin{array}{c}1\\ 2\end{array}\right]u
\end{align*}
$$

In [4]:
F = np.matrix([[0,1],[-3,-7]])
np.linalg.eig(F)

(array([-0.45861873, -6.54138127]),
 matrix([[ 0.90896654, -0.15111729],
         [-0.41686908,  0.98851584]]))

A função "eig()" retorna os autovalores de uma matriz, assim como um conjunto de autovetores correspondentes. No nosso caso, apenas os autovalores importam. Como se pode ver, os dois autovalores são reais e negativos, logo, o sistema é assintoticamente estável. 