# Forma de Jordan ou Modal
<p align="center">
<img src="Fig7.8.svg" width="80%"/>
</p>

Na forma modal, os estados aparecem majoritariamente desacoplados, isto é, uma equação de estados depende basicamente apenas da sua própria variável de estado.

Isso é verdade sempre que o sistema tiver pólos reais e distintos. 

Quando o sistema tiver pólos repetidos, haverá um pequeno acoplamento, mas apenas entre os estados referentes ao mesmo pólo (autovalor).

Quando o sistema tiver pólos imaginários, as equações podem ser desacopladas, mas ao custo de ganhos imaginários. Para eliminar os ganhos imaginários, podemos introduzir um pequeno acoplamento, mas apenas entre os estados associados aos autovalores conjugados.

Para o sistema da Fig 7.8. 
$$
\begin{align}
    \dot{z}_1 &= u - 4z_1\\
    \dot{z}_2 &= u - 3z_2\\
    y &= 2z_1-z_2
\end{align}
$$

Uma consequência do desacoplamento é que matriz $\mathbf{F}$ se torna **diagonal**.
$$
\begin{align}
    \dot{\mathbf{x}} &= \left[\begin{array}{rr}-4 & 0\\0 & -3\end{array}\right]\mathbf{x}+\left[\begin{array}{r}1\\1\end{array}\right]u\\
    y &= \left[\begin{array}{rr}2 & -1\end{array}\right]\mathbf{x}
\end{align}
$$

A forma modal é útil para determinar rápida e intuitivamente a controlabilidade. O sistema é não-controlável quando o sinal de controle não consegue "chegar" até um determinado integrador por nenhum caminho. 

Algumas observações importantes:

1. Um sistema pode perder controlabilidade quando na sua função de transferência há algum cancelamento entre pólos e zeros.
2. Para achar a forma modal a partir da função de transferência, use expansão em frações parciais

## Para achar a forma modal (pólos reais e distintos)
* Ache a expansão em frações parciais da função de transferência
* Faça um diagrama para cada uma das parcelas da expansão
* Nomeie os estados (saída dos integradores) e monte as equações normalmente

**Mais um exemplo de modal**

$$
\begin{align}
    G(s) &=\frac{s+3}{(s+1)(s+5)(s-9)}
\end{align}
$$

Precisamos primeiro expandir e achar os resíduos (frações parciais)

In [1]:
import scipy.signal as sig
import numpy as np

num = [1,3]

# As duas próximas calculam o denominador
den = np.convolve([1,1],[1,5])
den = np.convolve(den,[1,-9])
#sympy.apart()

# Acha os resíduos. Funciona bem se não tiver pólos repetidos!
r,p,k = sig.residue(num,den)
print(r)
print(p)


[-0.05       -0.03571429  0.08571429]
[-1. -5.  9.]


Logo:
$$
\begin{equation}
    G(s) = \frac{-0.05}{s+1}-\frac{0.03}{s+5}+\frac{0.08}{s-9}
\end{equation}
$$

O diagrama para a representação de cada modo está a seguir


<p align="center"><img src="modal1.svg" width="50%" center> </p>


As equações de estado vão ser (**verifique você mesmo!**):
$$
\begin{equation}
    \dot{x}_1 = -x_1-0.05u
\end{equation}
$$

$$
\begin{equation}
    \dot{x}_2 = -5x_2-0.03u
\end{equation}
$$

$$
\begin{equation}
    \dot{x}_3 = 9x_3+0.08u
\end{equation}
$$

A equação de saída é:
$$
\begin{equation}
    y = x_1+x_2+x_3
\end{equation}
$$

Por fim, a representação matricial:
$$
\begin{equation}
    \dot{\mathbf{x}} = \left[\begin{array}{rrr}
    -1 & 0 & 0\\
    0 & -5 & 0\\
    0 & 0 & 9
    \end{array}
    \right]\mathbf{x} +
    \left[\begin{array}{r}
    1 \\
    1 \\
    1 
    \end{array}\right]u
\end{equation}
$$

$$
\begin{align}
    y = \left[\begin{array}{ccc}-0.05 & -0.03 & 0.08\end{array}\right]\mathbf{x}
\end{align}
$$


**Exercício:** defina esse sistema no Python e simule uma resposta ao degrau

## Forma de Jordan com polos reais e repetidos

Suponha que:
$$
\begin{align}
    G(s) &= \frac{16s}{(s+3)^2(s+5)}
\end{align}
$$

Vamos calcular rapidamente os resíduos e a expansão:

In [3]:
num = np.array([16,0])

# As duas próximas calculam o denominador
den = np.convolve([1,3],[1,3])
den = np.convolve(den,[1,5])

# Acha os resíduos. 
r,p,k = sig.residue(num,den)
print(r)
print(p)


[ 20.+0.j -24.+0.j -20.+0.j]
[-3.+0.j -3.+0.j -5.+0.j]


Então:
$$
\begin{align}
    G(s) &= \frac{20}{(s+3)}-\frac{24}{(s+3)^2}-\frac{20}{s+5}
\end{align}
$$

Observe no diagrama como devemos implementar o termo quadrático:
<p align="center">
<img src="modal3.svg" width="80%">
</p>

Observe que os estágios correspondentes ao polo repetido ficam em série, e não em paralelo, diferente dos outros.

**Agora escreva a representação matricial!**

## Transformação de estado

A essa altura vc já deve ter percebido que um mesmo sistema, com uma única função de transferência, pode ter diferentes representações de estado (matrizes)

Quando mudamos de uma representação para outra, as matrizes mudam, e os estados **não são mais os mesmos**. Eles adquirem outro significado físico. No entanto, as características intrínsecas do sistema, tais como pólos, zeros, estabilidade e outras devem permanecer as mesmas.

A explicação matemática para isso é a teoria de transformações lineares.

Supondo que a representação "velha" seja:
$$
\begin{align*}
    \mathbf{\dot{x}} &= \mathbf{Fx+G}u\\
    y &= \mathbf{Hx}+Ju
\end{align*}
$$

A mudança para um novo vetor de estados, digamos $\mathbf{z}$, é representada por uma transformação linear:
$$
\begin{align*}
    \mathbf{x} &= \mathbf{Tz}
\end{align*}
$$
onde $\mathbf{T}$ é uma matriz quadrada de ordem $n$, inversível (ou seja, é possível "ir" e "voltar" com a mudança).

Esperamos que, usando o novo vetor de estados $\mathbf{z}$, a representação seja algo como:
$$
\begin{align*}
    \mathbf{\dot{z}} &= \mathbf{Az+B}u\\
    y &= \mathbf{Cz}+Du
\end{align*}
$$

Pode-se mostrar que a representação "nova" se relaciona com a "velha", usando a matriz de transformação $\mathbf{T}$ da seguinte forma:
$$
\begin{align*}
    \mathbf{A} &= \mathbf{T^{-1}FT}\\
    \mathbf{B} &= \mathbf{T^{-1}G}\\
    \mathbf{C} &= \mathbf{HT}\\
    D &= J
\end{align*}
$$

A transformação para forma de Jordan, em particular, é um procedimento que chamamos de diagonalização

## Dica útil: Matriz inversa de segunda ordem

Para fazer transformações em sistemas de ordem 2, precisamos da inversa da matriz de transformação.

Um regra rápida para achar a inversa de 2a ordem é:
1. Troque a ordem dos elementos da diagonal principal
2. Inverta o sinal dos elementos não diagonais
3. Divida a matriz inteira pelo determinante da matriz original (supondo que ele não é zero)

$$
\begin{align}
    \left[\begin{array}{cc} a&b\\c&d \end{array}\right]^{-1} &= \frac{\left[\begin{array}{cc} d&-b\\-c&a \end{array}\right]}{ad-bc}
\end{align}
$$

**Lembre-se que isso só vale para matriz de ordem 2!**



**Exemplo**: Transforme o sistema
$$
\begin{align*}
    \dot{\mathbf{x}} &= \left[\begin{array}{rr}-4 & 0\\0 & -3\end{array}\right]\mathbf{x}+\left[\begin{array}{r}1\\1\end{array}\right]u\\
    y &= \left[\begin{array}{rr}2 & -1\end{array}\right]\mathbf{x}
\end{align*}
$$

Para os estados $\mathbf{z}$, onde:
$$
\begin{align*}
    {\mathbf{x}} &= \left[\begin{array}{rr}8 & 1\\3 & 5\end{array}\right]\mathbf{z}
\end{align*}
$$

Do problema, sabemos que:
$$
\begin{align*}
    {\mathbf{T}} &= \left[\begin{array}{rr}8 & 1\\3 & 5\end{array}\right]
\end{align*}
$$

Podemos calcular logo a inversa:
$$
\begin{align*}
    {\mathbf{T}^{-1}} &= \frac{\left[\begin{array}{rr}5 & -1\\-3 & 8\end{array}\right]}{37}
\end{align*}
$$

O resto dos cálculos podemos agilizar com Python:

In [7]:
T = np.matrix([[8,1],[3,5]])
F = np.matrix([[-4,0],[0,-3]])
G = np.ones((2,1))
H = np.matrix([2,-1])
iT = np.linalg.inv(T)

Fnovo = np.matmul(np.matmul(iT,F),T)  # (iT @ F) @ T
Gnovo = np.matmul(iT,G)
Hnovo = np.matmul(H,T)

print(Fnovo)
print(" ")
print(Gnovo)
print(" ")
print(Hnovo)


[[-4.08108108 -0.13513514]
 [ 0.64864865 -2.91891892]]
 
[[0.10810811]
 [0.13513514]]
 
[[13 -3]]


**Exercício**: para a função de transferência
$$
\begin{align*}
    G(s) =\frac{3s^2-1}{(s+1)(s+7)(s+5)}
\end{align*}
$$

1. Faça o diagrama de blocos da forma de controlador
2. Obtenha as matrizes da forma de controlador
3. Obtenha as matrizes da forma modal
4. Ache as matrizes se aplicada a transformação
$$
\begin{align*}
    \mathbf{T} =\left[\begin{array}{cc}1&-1\\1&1 \end{array}\right]
\end{align*}
$$
